### ISSUE TITLE
How to: left align all chat messages

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1065]
What is the recommended way to align all messages (both incoming and outgoing) to the left side of screen? I want to customize the behavior of having the incoming messages on one side and the outgoing messages on the other.

SDK version: StreamChatUI v3.2.0-beta.9

**Comment by b-onc** [comment]
Hello @srgray 
In the current `beta` version, the message cells are not implemented to be easily aligned. The recommended way is to implement your own cell and use it.
However, since we've seen this request many times, we've re-engineered the message list layout system so this usecase is easily supported. Part of the solution is already merged in `main`. We'll be releasing a new beta with this new system soon. When we do that, I'll update this ticket with the new suggested solution.

**Comment by b-onc** [comment]
Hello @srgray  

This is possible using our own Message cells with 4.0-beta.1.
You just need to do:
```swift
class LeftAlignedMessageLayoutOptionsResolver: ChatMessageLayoutOptionsResolver {
    override func optionsForMessage(at indexPath: IndexPath, in channel: _ChatChannel<NoExtraData>, with messages: AnyRandomAccessCollection<_ChatMessage<NoExtraData>>) -> ChatMessageLayoutOptions {
        var options = super.optionsForMessage(at: indexPath, in: channel, with: messages)
        options.remove(.flipped)
        options.insert(.avatar)
        return options
    }
}
```

And before you display your Chat screen...
```swift
Components.default.messageLayoutOptionsResolver = LeftAlignedMessageLayoutOptionsResolver()
```

and it looks like:
<img width="487" alt="Screen Shot 2021-05-21 at 19 55 42" src="https://user-images.githubusercontent.com/770464/119178997-b1609d80-ba6e-11eb-92c0-3ebdce975c51.png">

**Comment by borut-t** [comment]
How can I do this with SwiftUI SDK?
