### ISSUE TITLE
4.0.0-beta.6: Chat messages aligned to bottom instead of top

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1275]
## What did you do?
View Chat messages in `ChatMessageListVC`

## What did you expect to happen?
I expected the chat messages to be displayed from top->bottom, as it has worked in previous beta versions.

## What happened instead?
The chat messages are displayed from bottom->top. For example, if there are only 2 chat messages (not enough to fill screen), those 2 chat messages appear at the bottom of the `UITableView`, instead of the top.

Is there anyway to customize this behavior back to the old top->bottom way?

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.6
**GetStream Chat frameworks:** StreamChat, StreamChatUI

**Comment by petyosi** [comment]
Hey @srgray,

Thanks for bringing this to our attention. The change is deliberate. The chat interfaces we look at as a reference implementation keep that alignment to the bottom. It would be great if you can share your use case with us, so that we can keep that in mind for future development.

We will investigate the possibility to provide such configuration and post updates here. Thanks!

**Comment by srgray** [comment]
OK, understood. I don't have much more information to provide about our use case, other than the preference that messages are displayed top-down (or could be configured to do so). Thanks!
