### ISSUE TITLE
ChatMessageListVC Crashes

### ISSUE THREAD

**Issue by elemanhillary** [GetStream/stream-chat-swift#1280]
How to reproduce error

- create an instance of ChatMessageListVC
- make sure the channel id has no messages
- send first message and scroll

This also happens when you create new channel and send first message

pod version ```4.0.0-beta.6```

Then it will crush with
```Terminating app due to uncaught exception 'NSRangeException', reason: 'Attempted to scroll the table view to an out-of-bounds row (1) when there are only 1 rows in section 0. Table view: <_TtGC12StreamChatUI20_ChatMessageListViewV10StreamChat11NoExtraData_: 0x7fd4790f6000; baseClass = UITableView; frame = (0 0; 414 750); transform = [1, 0, 0, -1, 0, 0]; clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600002bcaa60>; layer = <CALayer: 0x60000258b380>; contentOffset: {0, 22}; contentSize: {414, 66}; adjustedContentInset: {-22, 0, 8, 0}; dataSource: <swap.MyChannelVC: 0x7fd47a073570>>'```

**Comment by elemanhillary** [comment]
Note: its a duplicate of #1261

**Comment by evsaev** [comment]
Hey there 👋 

The crash is already fixed in https://github.com/GetStream/stream-chat-swift/pull/1262 and will be published soon with `4.0.0-beta.7`. 

In the meantime, you can use `release/preview` branch which is identical to `4.0.0-beta.6` but with some crashes fixed (including this one) or `main` to get the latest state of `StreamChat/StreamChatUI` SDKs
