### ISSUE TITLE
How to: Filter ChatChannelListVC based on a user search string

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1411]
## What did you do?
I'm trying to filter the channels that are displayed by `ChatChannelListVC` based on a user search string. Here's what I have tried:
- Every time user changes search string, create a new `ChatChannelListController` with the appropriate `query` filter
- Assign that new controller to `ChatChannelListVC.controller`

## What did you expect to happen?
I expected that the list of channels displayed in `ChatChannelListVC` would be updated to match the new query filter

## What happened instead?
The list of channels displayed does not update to match the new query filter

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.11
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
See attached sample project
[StreamChannelSearch.zip](https://github.com/GetStream/stream-chat-swift/files/7067352/StreamChannelSearch.zip)

**Comment by nuno-vieira** [comment]
Hi @srgray! 

Thank you for the report! 

I will take a look into it and update you as soon as I've more details on my side 🙂

**Comment by nuno-vieira** [comment]
Hello @srgray!

The list of channels doesn't get updated because the query is actually not correct on the sample project you provided, and so it returns empty results. The reason is that the name being used on the filter is the name of the channel and not the member's name.

To make the query work for now you can add a custom filter like this since we don't support it yet out of the box:
```swift
extension FilterKey where Scope: AnyChannelListFilterScope {
    static var memberName: FilterKey<Scope, String> { "member.user.name" }
}
```
Then you can use it on your search query:
```swift
let searchTextFilter: Filter<ChannelListFilterScope> = .autocomplete(.memberName, text: searchText)
```

With this in place, it should work. But keep in mind this is a bit of a workaround and can have unexpected behaviour. Currently, the iOS SDK only supports searching users officially, but we are actually working on the search functionality of other entities and probably will have more news soon. Until then you can use this workaround with the possibility of having issues, so I would recommend testing it extensively.

Let me know if you have any more questions 🙂

**Comment by srgray** [comment]
@nuno-vieira Thanks for the reply. But I actually _do_ want to search for Channel `name` property. I would like to filter my channels by their channel names.

**Comment by nuno-vieira** [comment]
Hello @srgray! I see, I misunderstood then, sorry! I will investigate then why the query is not working. But as I said, this is not officially supported, so bugs like not showing empty results are expected. Sorry for the inconvenience! We are actively working right now on search functionality and we should have updates soon.

**Comment by nuno-vieira** [comment]
@srgray So the reason the query doesn't work is that not all channels have names. So if you try to search for "QA" instead of "Gray", the result will include the "New QA Group", because there is a channel with `name = "New QA Group"`. On the other hand, the channels that have "Gray" as their names, the name is actually computed on the SDK side by the `ChatChannelNamer` where the member's names are used to compose the channel name. So one possible working query is this one:

```swift
let searchTextFilter: Filter<ChannelListFilterScope> = Filter.or([
    .autocomplete(.name, text: "Gray"),
    .autocomplete(.memberName, text: "Gray")
])
```

The problem here is all members of the channel will be queried, and not the member who appears on the channel name only. If this doesn't work for you, we will need to investigate and see what is the best way to query the channels the way you want.

**Comment by srgray** [comment]
OK, I think we are willing to wait until the new search feature comes out in the iOS SDK
