### ISSUE TITLE
`unreadCountPublisher` publishes only an initial value (and always zero).

### ISSUE THREAD

**Issue by cjmconie** [GetStream/stream-chat-swift#1447]
## What did you do?

Subscribe to `currentUserController`'s `unreadCountPublisher` and receive only initial values of 0. 

To reproduce:

Inside `DemoAppCoordinator` update `presentChat(userCredentials, channelID)` implementation of `connectUser` as follows:
```swift
        ChatClient.shared.connectUser(
            userInfo: .init(id: userCredentials.id, name: userCredentials.name, imageURL: userCredentials.avatarURL),
            token: token
        ) { error in
            if let error = error {
                log.error("connecting the user failed \(error)")
                return
            }
            self.setupRemoteNotifications()
            
            // ----------TEST-----------
            // print out the non-publisher values for comparison
            print("[TEST] unreadCount: \(ChatClient.shared.currentUserController().unreadCount)")
            
            // synchronise (as suggested here: https://github.com/GetStream/stream-chat-swift/issues/1224#issuecomment-876388294)
            ChatClient.shared.currentUserController().synchronize { [weak self] error in
                guard let self = self else { return }
                if let error = error {
                    print("[TEST] synchronize error: \(error)")
                }
                
                // This does not work because the data controller is in state `.initialized` and so `startObservingIfNeeded` returns early?
                // Seems related to: https://github.com/GetStream/stream-chat-swift/issues/1224
                ChatClient.shared.currentUserController().unreadCountPublisher.sink { completion in
                    print("[TEST] unreadCountPublisher completion: \(completion)")
                } receiveValue: { unreadCount in
                    print("[TEST] unreadCountPublisher value: \(unreadCount)")
                }.store(in: &self.cancelBag)
            }
            // ----------TEST-----------
        }
```

## What did you expect to happen?
The `unreadCountPublisher` publisher to publish appropriate values. (Same applies to `currentUserChangePublisher`)

## What happened instead?
The publishers fire with initial values of 0. The non-publisher version `ChatClient.shared.currentUserController().unreadCount` outputs the correct values.

## GetStream Environment
**GetStream Chat version:** 4.0.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 14.0
**Swift version:** 5.4.2
**Xcode version:** 13 beta 5
**Device:** Any

**Comment by tbarbugli** [comment]
The fact that the completion block is not called is indeed strange and something we'll look into it. Besides it is OK to move 

```swift
ChatClient.shared.currentUserController().unreadCountPublisher.sink { completion in
            print("[TEST] unreadCountPublisher completion: \(completion)")
        } receiveValue: { unreadCount in
            print("[TEST] unreadCountPublisher value: \(unreadCount)")
        }
```

outside the `ChatClient.shared.currentUserController().synchronize` completion block. Keep in mind that when you do that the initial value will always be 0 because this will be executed before the user connection is estabilished.

Here's an example on how to get the unread count once the connection is OK

```swift
ChatClient.shared.connectUser(
    userInfo: .init(id: userCredentials.id, name: userCredentials.name, imageURL: userCredentials.avatarURL),
    token: token
) { error in
    if let error = error {
        log.error("connecting the user failed \(error)")
        return
    }
    print("[TEST] unreadCount: \(ChatClient.shared.currentUserController().unreadCount)")
}
```

**Comment by tbarbugli** [comment]
@cjmconie the reason the syncronize was not called is because the controller instance was not stored anywhere else than in the stack you shared.  

If creating a reference to `ChatClient.shared.currentUserController()` (ie. class var) works then. This is very easy to get "wrong" and we might create a strong reference to avoid callbacks from being collected and never executed (see https://github.com/GetStream/stream-chat-swift/pull/1462).

I am closing this for now, feel free to comment/re-open if needed
