### ISSUE TITLE
NukeImageLoader class can't be used

### ISSUE THREAD

**Issue by vladpre92** [GetStream/stream-chat-swift#1562]
## What did you do?
Tried to make a subclass of NukeImageLoader, but could not use it with Components.

## What did you expect to happen?
To have public initializer and use it with Components.

## What happened instead?
Protected initializer.

## GetStream Environment
**GetStream Chat version:** 4.1.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 15.0
**Swift version:** 5
**Xcode version:** 13
**Device:** Any

## Additional context
I tried to subclass NukeImageLoader in order to insert a middleware for securing our backend media urls used as channel avatars, user avatars etc. Basically, if the url is non StreamChat, and I receive error codes like 401 I can do a jwt refresh with our backend.

Is this the indended behaviour? If so, I don't see a point in leaving NukeImageLoader's methods marked with `open` access modifier.

**Comment by adamrushy** [comment]
@vladpre92 yeah I see what you mean, we don't really have a requirement as it's designed to be out of the box but then we provide the interface for loading images. I will close the thread as you mentioned but do let us know if you see anything else because we could probably do with tidying this part of the SDK up.

**Comment by vladpre92** [comment]
Thank you!

**Comment by nuno-vieira** [comment]
@vladpre92 Thanks again for the report! The fix is now available on main and will come out in the next release 👍
