### ISSUE TITLE
Composer input occluded by keyboard in SwiftUI VStack

### ISSUE THREAD

**Issue by cjmconie** [GetStream/stream-chat-swift#1570]
## What did you do?

Added `ChatChannelListVC` inside a `VStack`. Example use case, adding a bottom tab bar view.

The code snippet below demonstrates the issue. Simply update `MessengerChatChannelList` in the Messenger clone to reproduce it.

```swift
struct MessengerChatChannelList: View {
    
    @State var channels: [ChatChannel] = []
    
    var body: some View {
        VStack(spacing: 0) {
            NavigationView {
                ChatChannelListVC.asView(
                    ChatClient
                        .shared
                        .channelListController(
                            query: ChannelListQuery(
                                filter: .containMembers(
                                    userIds: [ChatClient.shared.currentUserId!]
                                )
                            )
                        )
                )
            }
            // A custom view, e.g. tab bar
            Rectangle()
                .frame(maxWidth: .infinity)
                .foregroundColor(.blue)
                .frame(height: 52)
                .overlay(Text("Tab Bar"))
            
        }
        .ignoresSafeArea(.keyboard, edges: .bottom) // this is necessary, otherwise the VStack is pushed up by the keyboard.
        .navigationBarTitleDisplayMode(.inline)
        .navigationTitle("Chats")
        
    }
}
```

## What did you expect to happen?

The composer input field to remain above the keyboard allowing user input.

## What happened instead?

The composer view gets occluded by the keyboard.

## GetStream Environment
**GetStream Chat version:**  StreamChatUI (4.1.0)
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** iOS 15
**Swift version:** 5.5
**Xcode version:** 13.0
**Device:** iPhone 12, iPhone 8

**Comment by nuno-vieira** [comment]
Hi @cjmconie! 

Yes as @martinmitrevski we have a new SwiftUI SDK that might be useful for you 🙂 

Anyways, unfortunately, the current keyboard handler tries to handle the most common cases, but for this particular case, I'm afraid it won't work because yours is a bit special. Our keyboard handler relies a lot on AutoLayout and it does work with a UIKit TabBar but not embedded in a customer SwiftUI view. What you can do is to provide a custom `KeyboardHandler` in the `ChatChannelVC` and `ChatThreadVC`. The `KeybaordHandler` is a protocol so that you can provide your custom class. You probably can get inspiration from the default `ComposerKeyboardHandler` and adjust to your needs 👍

The SwiftUI Wrappers are indeed a bit limited in functionality. The SwiftUI SDK is a much better option if you need fine grainer control 👍 

Thanks!
