### ISSUE TITLE
ChatChannel watchersCount property wrong value for some channels

### ISSUE THREAD

**Issue by vladpre92** [GetStream/stream-chat-swift#1585]
## What did you do?
Download 4.2.0 StreamChat demos from StreamChat repository.
Run StreamChatSample target.
From channel list select Adella channel. Same for IOS Group channel an others.

## What did you expect to happen?
The channel screen to have the actual number of online users.

## What happened instead?
The channel screen had wrong number of online users.

## GetStream Environment
**GetStream Chat version:** 4.2.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 15.0
**Swift version:** 5
**Xcode version:** 13.1
**Device:** Any iOS simulator and any device.

## Additional context
If you access one of the above mentioned channel member list screen, you can see there that actually only 1 user is online.
I also checked by putting some logs on `channelController(_ channelController: ChatChannelController, didUpdateChannel channel: EntityChange<ChatChannel>)` delegate method.

The logs look like this:
`lastActiveWatchers: Optional([StreamChat.ChatUser])`
`watchersCount: Optional(2)`
`lastActiveMembers.count where isOnline == true: 1, active name list: [Optional("Luke Skywalker")]`

I can also reproduce this on my project, but I wanted to reproduce it also on your demo apps. In my case it happens only when presenting ChatChannelVC subclass manually without going trough channel list screen.

My code look like this:
```
let channelVC = ChatChannelViewController()
channelVC.presentationSource = .direct
channelVC.channelController = ChatClient.shared.channelController(for: cid)
navigationController?.pushViewController(channelVC, animated: true)
```

The above code is called after I'm sure that I am connected to StreamChat server.

Here is a video to demonstrate the above behaviour:

https://user-images.githubusercontent.com/3681654/139095743-9ba04f12-aa05-41e8-8e16-0cc62f8e7fc6.mp4

Thank you!

**Comment by b-onc** [comment]
Hello @vladpre92 ,

I've checked and confirmed that this is not a bug.

You see, channel watchers and online members are 2 different lists. A "watcher" doesn't have to be a "member" (although does need to be online), any user can watch any channel (if permissions permit)

By default, StreamChat SDK doesn't request watchers of a channel. To do so, `channelController` should be created like so:
```swift
client.channelController(
            for: ChannelQuery(cid: cid, watchersLimit: 100)
)
```
by default, SDK uses `watchersLimit: 0`

When you create the `channelController` for channel "Adella" like so, you'll see the following:
```
watcherCount 2 
watchers ["luke_skywalker", "leia_organa"]
onlineMembers ["luke_skywalker"]
```
User `leia_organa` is watching the channel, although they're not a member of this channel. This is mainly possible since we have disabled permissions in our DemoApp.

When you want to have a UI like Telegram (X members, Y online), using default permissions, you can safely use `watcher_count` as a replacement for online member count. If you see an issue regarding this _in your own Stream app_, please open a ticket and we'll be glad to help you out.
