### ISSUE TITLE
Not able to customize ChatMessageContentView due to ChatMessageActionsTransitionController

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1639]
## What did you do?
I tried to customize `ChatMessageContentView` to display user's `extraData` property instead of `name`.

## What did you expect to happen?
I expect the SDK to handle the customization correctly for all cases.

## What happened instead?
Due to a recent change where `ChatMessageContentView` is recreated (and not reused) during `ChatMessageActionsTransitionController` presentation, the UI display of the property flickers.

## GetStream Environment
**GetStream Chat version:** 4.5.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
See attached sample project:
[StreamCustomizeMessageCell.zip](https://github.com/GetStream/stream-chat-swift/files/7583433/StreamCustomizeMessageCell.zip)
 
Sample project description:
This sample project shows our approach to replacing the display of user `name` property with user's `extraData` property `username` in the `ChatMessageContentView`. We need to be able to conditionally make this customization (based on user, channel, etc.) which is shown in the sample. To accomplish this, we pass down a flag `prefersUsername` through the StreamChatUI hierarchy.

Steps to reproduce:
- Run sample project
- Tap `Login as user1`
- Tap to enter the only chat channel
- Notice that (for user1), the sending author's `extraData.username` is displayed instead of the standard `name` property. This is working as we expect
- Long press on message to display the message actions UI
- Notice that the display of `extraData.username` is briefly replaced with the `name` property before being set back to `extraData.username`. This is the bug behavior

I've debugged it down to a recent change that was made in the SDK to recreate the message cell/content view instead of moving that view across hierarchies. It's this change that negatively affected our customization of this view.
Questions: Is there a better way for us to achieve this customization? Or can the bug in the SDK be fixed somehow?

**Comment by adamrushy** [comment]
Hey, @srgray thanks for reporting this to us. Just to say I am investigating this further and will get back to you soon 👍🏼

**Comment by adamrushy** [comment]
Hey, @srgray, I had a look into this issue for you. Firstly, thanks so much for providing the sample project. It was straightforward to reproduce and find the problem. We recently refactored this part of the code because previously, we were using the same `View` when displaying the actions; this wasn't ideal and caused us issues, so now we take a snapshot of the `View` and transition this. This is also much safer.

Unfortunately, because the "author display label" isn't a part of the ViewController's, it's not setting your custom text until the final transition to the _actual_ `View`. I think we can do better here and probably expose a "Display Name" available that would be used across the SDK, but let me ticket this up internally and discuss it with the team.

For now, you can implement the code below, which will make sure your text is set during the animation.

```
import StreamChatUI

class CNChatMessageActionsTransitionController: ChatMessageActionsTransitionController {
    /// The purpose of this override is to do everything in super, plus: transfer CN properties on messageContentView from original -> new
    override func animatePresent(using transitionContext: UIViewControllerContextTransitioning) {
        super.animatePresent(using: transitionContext)
        guard
            let toVC = transitionContext.viewController(forKey: .to) as? ChatMessagePopupVC,
            let originalMessageContentView = selectedMessageCell?.messageContentView
        else { return }
        
        // Set the custom authorNameLabel
        toVC.messageContentView.authorNameLabel?.text = originalMessageContentView.content?.author.usernameWithAtSymbol
        
        (toVC.messageContentView as? CNChatMessageContentView)?.prefersUsername = (originalMessageContentView as? CNChatMessageContentView)?.prefersUsername ?? false
    }
}
```

I hope this helps; let me know how you get on 👍🏼

**Comment by srgray** [comment]
This approach worked great, thanks for the help!
