### ISSUE TITLE
StreamChat SDK added using Tuist failing due to `StreamChatModel.xcdatamodeld`

### ISSUE THREAD

**Issue by Alexsilvacodes** [GetStream/stream-chat-swift#1840]
## What did you do?
Include StreamChat as dependency using [the new Dependencies feature for Tuist](https://docs.tuist.io/manifests/dependencies/)

## What did you expect to happen?
StreamChat SDK to be resolved correctly

## What happened instead?
StreamChat SDK gets resolved as expected (with `tuist fetch`) but it fails when adding it to the project when generating the project.
```
Trying to add a file at path /<project path>/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stream-chat-swift/Sources/StreamChat/Database/StreamChatModel.xcdatamodeld to a build phase that hasn't been added to the project.
```

## GetStream Environment
**GetStream Chat version:** 4.11.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** -
**Swift version:** Latest 5
**Xcode version:** 13.2.1
**Device:** -

**Comment by nuno-vieira** [comment]
Hi @Alexsilvacodes!

Are you sure this isn't a problem in Tuist? Is there any known issue on Tuist when using dependencies that have CoreData included?

Since our project works fine with SPM, Cocoapods and Carthage, I would assume this is actually a bug from Tuist. So it is probably worth creating an issue on their repo.

Best,
Nuno

**Comment by Alexsilvacodes** [comment]
Hey Nuno, definitely they are looking into it, I will close this issue as I already spoke with them.

Thank you for your response  🙏
