### ISSUE TITLE
Custom Reactions view causes problems with cell layout

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1845]
## What did you do?
I tried to replace the existing StreamChatUI Reactions view for a message with my own custom UI. (meant to mimic Slack reaction UI)

## What did you expect to happen?
I expected the message cell to still layout correctly.

## What happened instead?
The layout of the cell (and other cells) is off when displaying my custom Reactions UI view.

## GetStream Environment
**GetStream Chat version:** 4.11.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
See attached project:
[StreamEmojiReaction.zip](https://github.com/GetStream/stream-chat-swift/files/8235806/StreamEmojiReaction.zip)

Steps to reproduce:
- Run attached app
- Tap 'View Channel List'
- Tap channel to enter chat channel
- Long press on a message and choose the "🔥" reaction
- Notice the custom reaction UI below the chat message and how it causes the cell layout to mess up
- Toggling the reactions on/off on the messages will cause further layout issues

See video:
![Simulator Screen Recording - iPhone 13 Pro - 2022-03-11 at 15 24 50](https://user-images.githubusercontent.com/4721220/157974622-709eb3ff-7cb5-46d3-8f3b-31861d027ae0.gif)

**Comment by nuno-vieira** [comment]
Hi @srgray!

The message view needs a special treatment. If you introduce new views, you need to add a new `ChatMessageLayoutOption`. Because you are removing our own reactions, with your custom one, this is your use case. You can take a look on how to do this by following this section in the documentation: https://getstream.io/chat/docs/sdk/ios/uikit/components/message/#adding-new-views-and-functionality

Either way, I've make the changes for you in the example you provided, here is your example with my commit that basically follows that documentation:
[StreamEmojiReactionFixed.zip](https://github.com/GetStream/stream-chat-swift/files/8247415/StreamEmojiReactionFixed.zip)

Let me us know if you have any questions!

Best,
Nuno

**Comment by srgray** [comment]
@nuno-vieira Awesome! Thanks for the link to the docs and especially the change to the sample app!
