### ISSUE TITLE
Custom subview of ChatMessageContentView doesn't resize properly

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1902]
## What did you do?
I added a subview to `ChatMessageContentView` per docs: https://getstream.io/chat/docs/sdk/ios/uikit/components/message/#adding-new-views-and-functionality
I then tried to resize that view, based on its contents.

## What did you expect to happen?
I expected the subview to resize and the message cell to layout correctly.

## What happened instead?
My subview resized correctly but the message cell does not layout correctly:
![Simulator Screen Shot - iPhone 13 Pro - 2022-04-05 at 17 13 18](https://user-images.githubusercontent.com/4721220/161860522-17945aee-759e-4e8b-bec7-573159f2579a.png)

## GetStream Environment
**GetStream Chat version:** 4.11.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
Reference my original issue with adding the custom subview: https://github.com/GetStream/stream-chat-swift/issues/1845
See attached sample project:
[StreamEmojiReaction.zip](https://github.com/GetStream/stream-chat-swift/files/8422202/StreamEmojiReaction.zip)

Steps to reproduce:
- Open chat channel in sample project
- Added enough reactions to a message to require 2 lines to display them all in the subview's UICollectionView. 
- Notice the chat message cell doesn't layout correctly after the custom subview is resized to fit its contents

**Comment by nuno-vieira** [comment]
Hi @srgray!

Thank you for opening the issue! We will investigate this and will get back to you as soon as possible 👍 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @srgray!

Currently, this is not very easy to implement, especially if you want this to be dynamic. We would recommend for now using UIStackViews instead of a CollectionView. We have some customers who implemented slack-like reactions with 2 static stack views. Then if there are more than 2 rows, it will display "+more" just like Slack. I've made an implementation for you that uses dynamic stack views, with the con that it might not be that performant, especially with the current approach, for sure it can be optimized without building everything from scratch whenever the reactions update but this was just to show that it is possible.

[StreamEmojiReaction StackViews.zip](https://github.com/GetStream/stream-chat-swift/files/8444808/StreamEmojiReaction.StackViews.zip)

I hope that this unblocks you for now. We will in the near future provide a guide on how to do this customization since it is pretty common. And maybe even add it as out of the box and configurable. 

**Note:** In order for this to work, I enabled a flag `_messageListDiffingEnabled = true` in order for the cell to reload, otherwise it wouldn't because of our current message list implementation. Although the flag is marked as experimental, hence the `_` we have already customers using this and will soon turn it on by default, so it is safe to use it.

Best,
Nuno

**Comment by srgray** [comment]
@nuno-vieira Hi and thank you for the detailed example. Yes, this was very helpful. The `_messageListDiffingEnabled = true` was especially helpful.
Further question for you: my reaction item views will have a variable width. That's why I lean towards the UICollectionView, so that I can have a variable number of items per row, based on their widths. If I take my approach with UICollectionView and add in `_messageListDiffingEnabled = true`, the message cells seem to resize appropriately, as desired.
I'm just curious if you see any other potential problems with using the UICollectionView vs the UIStackViews?

**Comment by nuno-vieira** [comment]
Hi @srgray!

Were you able to implement this with a collection view? Looking at your implementation, you are using the collectionView.contentSize.height to set the height of the collection view. But this value is really only available after the cell reload. So I wonder how were you able to get this value properly before the cell finished reloading? 

Best,
Nuno

**Comment by srgray** [comment]
@nuno-vieira Going back through my commit history, it looks like I was never able to get the UICollectionView implementation working 100%, mostly like due to the issue you pointed out: I wasn't able to reliably size the UICollectionView to fit its contents. So I reverted to using your implementation with UIStackView.

**Comment by nuno-vieira** [comment]
Thanks for confirming @srgray!
