### ISSUE TITLE
Audio attachment doesn't display in attachment previews

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#1905]
## What did you do?
- go to the chat screen
- open Files
- select .mp3 file

## What did you expect to happen?
- selected .mp3 file should display in the attachment preview listing.

## What happened instead?
- It is showing blank attachment

## GetStream Environment
**GetStream Chat version:** 4.13.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.0.2
**Swift version:** 5.2
**Xcode version:** 13.2
**Device:** Iphone-XS

## Additional context

https://user-images.githubusercontent.com/47667077/162225244-2bcce339-d3f3-4603-821c-6f60c7b3774f.mp4

**Comment by nuno-vieira** [comment]
Hi @ajay-simform !

This happens because the iOS SDK currently doesn't support audio files, but it should fall back to a normal File for now, so this is indeed a bug. I'll open a quick PR for this one now, and so it will be fixed in the next release (next week).

Thank you for opening the issue!

Best,
Nuno

**Comment by bielikb** [comment]
Hi @ajay-simform,

we just released [new version of our SDK 4.14.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.14.0) that contains the fix for your reported issue.

Feel free to check it out right now!

Thanks again for your help! 🙌

Best,
Boris
