### ISSUE TITLE
Global chat search

### ISSUE THREAD

**Issue by teamsupermomos** [GetStream/stream-chat-swift#2013]
Most chat app has a global chat search (one at the top of chat channel directory) where you can search for particular keyword and the search result shows you all of its occurrence in all chat channels. You can also click it to quickly be redirected to that particular message.

Streamchat is a great product for both developers and end users but I think this is one of the most useful "basic" feature missing from the platform.

**Comment by nuno-vieira** [comment]
Hi @teamsupermomos!

This is something that is missing on the iOS UIKit SDK and we are going to work on it very soon actually. Right now is one of the most priority features we have coming in the next sprint. 

The search endpoint is already available in the Low-Level Client as well in case you would want to implement the UI yourself. But we understand it is not a simple task. 

Once we have this feature released, we will let you know 👍

We are sorry for the inconvenience.

I can see there's a discussion here as well: https://github.com/GetStream/stream-chat-swift/discussions/1764 so I will close this one because of duplication. Once we have this feature available we will post an update on the discussion 👍 

Best,
Nuno
