### ISSUE TITLE
Using custom Channel Array in ChatChannelListVC disturbs channel list UI

### ISSUE THREAD

**Issue by muaviyaijaz123** [GetStream/stream-chat-swift#2280]
## What did you do?
I assigned my own custom array of channels inside didChangeChannels function like:
    
     func controller(
        _ controller: ChatChannelListController,
        didChangeChannels changes: [ListChange<ChatChannel>]
    ) {
        listChangeUpdater.performUpdate(with: changes)
        customChannels = controller.channels.sorted(by: { $0.isPinnedByCurrentMember == true && $1.isPinnedByCurrentMember == false })
        
            private func getChannel(at indexPath: IndexPath) -> ChatChannel? {
        let index = indexPath.row
        controller.channels.assertIndexIsPresent(index)
        return customChannels[safe: index] // if i use controller.channels here it causes no issue but i want to use this array
    }

## What did you expect to happen?

I expected to see my list properly on screen

## What happened instead?

The item of channels List in some places goes blank like the following and sometimes all items gets shown:
 
<img width="356" alt="Screen Shot 2022-09-09 at 2 39 01 PM" src="https://user-images.githubusercontent.com/90596703/189322139-d533ea3c-a4dc-4748-b263-7188bf1dea96.png">

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by nuno-vieira** [comment]
Hi @muaviyaijaz123!

Sorry, but I'm not understanding what you are trying to do. I have a couple of questions:

1. Are you using the UI SDK of StreamChat or your own?
2. Why are you returning ` return customChannels[safe: index]`, if the function does not return anything?
3. You are using a `customChannels`, if that is your data source, you need to override all the collection view data source implementations, to return the `customChannels` instead.
4. The `performUpdate` will trigger a change in the collection view, you do that before changing the `customChannels`

The snippet you shared is very confusing and does not make much sense at all. If the only reason you are using a `customChannels` is because of ordering by `isPinnedByCurrentMember`, you should do that in the channel query. You can sort in the channel query.

Best,
Nuno

**Comment by muaviyaijaz123** [comment]
Hi @nuno-vieira,

I am trying to show channels in a certain order based on my variable (pinned ones at the top, rest below). For that i assign the controller.channels to my channels array in ChatChannelListVC didChangeChannels() function
after performUpdate. The problem is they do get sorted and also get on the top by doing above modifications in the code but some UI gets disturbed

The things you asked me :
 1. Yes, i am using using UI of stream SDK for channels list 
 display
 2. Before it had original implementation like this: 
      
      private func getChannel(at indexPath: IndexPath) -> ChatChannel? {
    let index = indexPath.row
    controller.channels.assertIndexIsPresent(index)
    return controller.channels [safe: index]

   So I replaced the return statemwnt with my customChannels. I wasn't sure because what to return here instead of controller.channels if I want to get my custom channel

3. Right now, i have just overridden the collection view's cellForitemAt as i was testing the display functionality in a certain order.

4. Yes  the original implementation before was just the perform update. After THAT there was nothing . So i thought to assign the stream channels to my array after the peformUpdate has happened

**Comment by polqf** [comment]
I guess the main problem here is that you are trying to have your own implementation for `getChannel(at:)`, but it is a private function, and you cannot alter it. Only open functions can be overridden by clients.

You cannot just return any channel you want based on a sorting that you perform on your side outside of the controller.
If you want any custom order, you have to use `ChannelListQuery`'s `sort`. Please check https://getstream.io/chat/docs/sdk/ios/uikit/components/channel-list/#sorting
