### ISSUE TITLE
Show dynamic size image inside a chat content

### ISSUE THREAD

**Issue by avijitmobi** [GetStream/stream-chat-swift#2300]
## What did you do?

I am passing the height and width of the image as **extraData** when sending a message then passing the aspect ratio in **galleryViewAspectRatio** variable inside **GalleryAttachmentViewInjector** inherited class. 

`override var galleryViewAspectRatio: CGFloat?{
        if ((contentView.content?.imageAttachments.count ?? 0) + (contentView.content?.videoAttachments.count ?? 0)) == 1, let json = self.contentView.content?.extraData, let width = try? json.toDictionary()["width"] as? Double, let height = try? json.toDictionary()["height"] as? Double{
            return CGFloat(width/height)
        }
        return super.galleryViewAspectRatio
    }`

## What did you expect to happen?

I want to show a dynamic size image in the ChatChannel Message list. When sharing a single image, I want to set this gallery preview height per the image's aspect ratio.

## What happened instead?

It loaded the image properly for the first time but when I scroll up and down it breaks the ratio. When I click and hold, chat content shows its original size, but when I release it, it breaks again. See the video for better clarification.

## GetStream Environment
**GetStream Chat version:**  4.21.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** 14.0
**Device:** iPhone 14 Pro Max Simulator

https://user-images.githubusercontent.com/17100639/190946577-88c5859f-befe-4a33-a581-95c1418dd496.mp4

**Comment by polqf** [comment]
Hi @avijitmobi ,

It looks like a cell height reuse problem. Let us investigate it, and will come back to you.

**Comment by nuno-vieira** [comment]
Hi @avijitmobi!

The first question from your code snippet is, what is `toDictionary()` doing on ExtraData? You can access the width property like so: `extraData["width"].numberValue`, which is much simpler than what you are doing right now. For more info, you can read the extra data docs here: https://getstream.io/chat/docs/sdk/ios/uikit/extra-data/

The reason that issue is happening is that whenever the cell is reused, it loses your custom width and height because the width and height come from your message extra data, so you need to set again the width and height whenever the cell is reused. In this case, you need to set the width and height in `GalleryAttachmentViewInjector.contentViewDidUpdateContent`. But for this, you will need to store the width and height constraints in a reference, and on `contentViewDidUpdateContent`, you update the value with the width and height from extra data.

Another question is, why are the width and height coming from the extra data? Is this a requirement from your app? It is usually recommended that images have the same consistent sizes to improve performance.

Either way, here is an example of how you should do this:

```swift
final class CustomGalleryAttachmentViewInjector: GalleryAttachmentViewInjector {
    override var galleryViewAspectRatio: CGFloat? { nil }

    var widthConstraint: NSLayoutConstraint?
    var heightConstraint: NSLayoutConstraint?

    override func contentViewDidLayout(options: ChatMessageLayoutOptions) {
        super.contentViewDidLayout(options: options)

        widthConstraint = galleryView.widthAnchor.constraint(equalToConstant: 0)
        widthConstraint?.isActive = true

        heightConstraint = galleryView.heightAnchor.constraint(equalToConstant: 0)
        heightConstraint?.isActive = true
    }

    override func contentViewDidUpdateContent() {
        super.contentViewDidUpdateContent()

        let width = contentView.content?.extraData["width"]?.numberValue ?? 0
        let height = contentView.content?.extraData["height"]?.numberValue ?? 0
        widthConstraint?.constant = CGFloat(width)
        heightConstraint?.constant = CGFloat(height)
    }
}
```

**Comment by avijitmobi** [comment]
Hi @nuno-vieira, yes, I have changed it, **extraData**  is also a dictionary. Thanks for this.

For the fixed height width problem,
Yes, It is a requirement for the app where I need to show a post without cropping means, I need to maintain the ratio. I will try your suggestion and apply it to our code and respond to you.

Do you think is there any other way I can fix the height constraint respective width of **contentView** of the cell except passing height and width through **extraData**?

**Comment by nuno-vieira** [comment]
@avijitmobi can you show the implementation of your `toDictionary()`? This could cause performance issues if done incorrectly. 

Currently, this is the only way. Table and Collection view cells are based on content. In your case, width and height are content as well, so you will always need to keep updating the constraints based on your width and height.

Best,
Nuno

**Comment by avijitmobi** [comment]
Hi, @nuno-vieira Double thanks to you. I followed your suggestion and its works fine. 

toDictionary is just a Json Serialization function. I have also removed it form my code. There is no need for it.

```
func toDictionary(_ encoder: JSONEncoder = JSONEncoder()) throws -> [String: Any] {
        let data = try encoder.encode(self)
        let object = try JSONSerialization.jsonObject(with: data)
        guard let json = object as? [String: Any] else {
            let context = DecodingError.Context(codingPath: [], debugDescription: "Deserialized object is not a dictionary")
            throw DecodingError.typeMismatch(type(of: object), context)
        }
        return json
    }
```

**Comment by nuno-vieira** [comment]
Hi @avijitmobi!

Glad it worked! 

You should definitely not do that serialization since it will impact the performance of the message list. 

Thanks,
Nuno
