### ISSUE TITLE
Open Channels / Group Invites / WhatsApp Group links

### ISSUE THREAD

**Issue by tr736-reclip** [GetStream/stream-chat-swift#2330]
## What are you trying to achieve?
What i would like to be able to do is have an "open chat" where anybody can join if they know the CID.  but i cant find support for this in the docs 

Use Case:-
User in app sends an "Group" invite to users x, y and z via a Deeplink. This Deeplink will contain a ChannelID.
Once the user Installs the app and has signed up the Deeplink object is consumed and the user is placed into the channel.

The deeplinking we can do. It's having the ability for anybody to join a channel if they know the CID.

Think of this as an invite link. that you get on WhatsApp that when consumed directs and opens up the group.

## If possible, how can you achieve this currently?
Possibly with permissions, but I need to give anonymous users join-channel rights?

**Comment by polqf** [comment]
Hi @tr736-reclip ,

If I understand you correctly, you want to create/edit a channel type so that it allows anyone to join it.

For that, you can go to Users and Permissions (`https://dashboard.getstream.io/app/<your-app-id>/chat/rolespermissions/roles`). In `scope`, select the channel type you want to edit.

Once there, you'll have a list of the available `Role`s and permissions for this channel.
Just click on `Edit` for the role you want to edit, and add `Join Own Channel` as a Grant. Save the changes, and you should be ready to go.

**Comment by polqf** [comment]
Given the inactivity, we'll assume this issue has been solved.
