### ISSUE TITLE
Is there a way to filter channels to get only unreads ones ?

### ISSUE THREAD

**Issue by BarragaoA** [GetStream/stream-chat-swift#2413]
## What are you trying to achieve?
Hello, I'm trying to fetch all channels having unread messages.

## If possible, how can you achieve this currently?
 I can do it using `channelListController(query: ChannelListQuery`), and then filtering from my side thanks of the result of the func `synchronize(_ completion: ((_ error: Error?) -> Void)? = nil)` 

```
controller.synchronize { error in
        if error != nil {
            completion(.failure(error!))
            return
        }
        
        let unreadChannels = controller.channels.filter {
            $0.isUnread
        }
   
        completion(.success(unreadChannels))
}
```

## What would be the better way?
Filtering directly thanks to the ChannelListQuery maybe like that :
```
hannelListQuery(filter: .and([.containMembers(userIds: [userId]),
                                                  .greater(.unreadMessagesCount, than: 0)],
                                     sort: [.init(key: .hasUnread, isAscending: false)],
                                     pageSize: 20)

```
Currently we can not do it because .unreadMessagesCount/.unreadChannelsCount do not conform AnyUserListFilterScope protocol. 
I try to extend `FilterKey where Scope: AnyChannelListFilterScope ` without success. Maybe there is already a way to do it but I did not find it.

## GetStream Environment
**GetStream Chat version: 4.24.0**
**GetStream Chat frameworks:** StreamChat, StreamChatUI

Thanks for your help.

**Comment by alteral** [comment]
Hi @BarragaoA,

Unfortunately, we do not support filtering by `unreadCount` at the moment. All available channel fields that can be used to filter query results can be found [here](https://getstream.io/chat/docs/ios-swift/query_channels/?language=swift&q=filter#channel-queryable-built-in-fields).

You would probably need to keep doing it locally. But, since if it's in `synchronize` it's only called once, it would be better to do it in the delegate method:

```swift
public func controller(
    _ controller: ChatChannelListController,
    didChangeChannels changes: [ListChange<ChatChannel>]
)
```

Hope this helps!

Best wishes,
Alexey

**Comment by BarragaoA** [comment]
Hi @alteral 

Thanks for your answer 👍

Best wishes,
Arnaud
