### ISSUE TITLE
Intermittent 401s on launch

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2431]
sometimes on launch, i'm seeing this 401 error

![Screenshot 2023-01-03 at 7 20 02 PM](https://user-images.githubusercontent.com/3814772/210479434-6ecf96fe-fd98-4a3e-b492-fbe19b24b039.png)

i'm still able to view the thread list, and send messages, etc.
not sure if this is expected, but i'm surprised to see these 401s

this is on 4.25.0

**Comment by polqf** [comment]
Hi @AndrewSB,

Are you waiting until a successful connection completion before fetching the channels?
By the error, it seems like you are trying to fetch the channels before connecting and having a valid token

**Comment by AndrewSB** [comment]
i double checked our sequencing, we are waiting for the connection to open before fetching controllers. by debugging the network traffic, i've noticed something i didn't expect

![Screenshot 2023-01-05 at 1 18 07 PM](https://user-images.githubusercontent.com/3814772/211401571-3daebb84-a5a8-4ffe-90d0-2a6fe3024e44.png)

these are the stream requests made in first 10 seconds after the app launch. you can see that the first 4 succeed (they have the Authorization header in the request), then for some reason the 5th doesn't include that header

any ideas on why the SDK would be doing that?

**Comment by nuno-vieira** [comment]
CC @polqf

**Comment by polqf** [comment]
@AndrewSB , could you please share code snippets to see your flow from opening the app until it is presenting the channel list? I was testing it in our Demo App, and I can only see 1 call to `/channels`

**Comment by AndrewSB** [comment]
hmm yeah that might be challenging since we use it at a bunch of places now. i can try, but easier yet - if i sent you the stream debug logs, could you tell from that?

if not, i can try to grok our integration to see where and when we're making our stream calls

**Comment by polqf** [comment]
The problem with logs with an issue like this is that they will not be able to determine what triggers those calls. We can try with those, but it would be better if you can provide the actual code.

**Comment by alteral** [comment]
Hi @AndrewSB,

As mentioned above, could you please share the actual code so we could proceed investigating the issue?

Best,
Alex

**Comment by AndrewSB** [comment]
getting back to this now, i'm not exactly sure what code's making this happen, we have stream code in a couple places

i've put a breakpoint on APIClient.swift:178, to here's the trace before the SDK tries to make a request with empty headers (so no authorization header)

<img width="804" alt="Screenshot 2023-02-14 at 4 13 32 PM" src="https://user-images.githubusercontent.com/3814772/218892350-fadc05c1-74f2-4a50-acb6-9b9e8cdec2ef.png">

and your `debug` level logs, right before that request is sent out

```
2023-02-14 16:10:45.967 [DEBUG] [main] [ChannelListController.swift:87] [channelListObserver] > didChangeChannels: ["Update (4, 0) - (cid:messaging:62FC19C5-40A5-4552-A921-449F2F6633FF)", "Update (10, 0) - (cid:messaging:EACE5D18-2B7F-4164-9B49-673A30E6AAFB)", "Update (5, 0) - (cid:messaging:A51F07BA-1B80-4F69-90A1-15B284792E45)"]
2023-02-14 16:10:45.999 [INFO] [main] [OfflineRequestsRepository.swift:107] [runQueuedRequests(completion:)] > Done executing all queued offline requests
2023-02-14 16:10:45.999 [INFO] [com.stream.sync-repository (QOS: UNSPECIFIED)] [SyncRepository.swift:147] [syncLocalState(lastSyncAt:completion:)] > Finished recovering offline state
2023-02-14 16:10:45.999 [DEBUG] [main] [APIClient.swift:279] [exitRecoveryMode()] > Leaving recovery mode
2023-02-14 16:10:45.999 [INFO] [main] [ConnectionRecoveryHandler.swift:157] [webSocketClient(_:didUpdateConnectionState:)] > Local state sync completed
```

here's our wrapper for most of our stream operations https://gist.github.com/AndrewSB/d1062b1912e6ea7d1db0147fd40a7dc7


any ideas?

**Comment by polqf** [comment]
Hi @AndrewSB, sorry for the delay here.

I can see that in `connectUser` you are not waiting for `connectUserImpl`.

This is likely to be the root cause of the issue. You are creating a controller, while the SDK is not fully set up. Therefore, it has no authentication in place and will return 401 on launch.

```swift
    public func connectUser() {
        Publishers.CombineLatest(userManager.getMe(), getReclipChatToken())
            .sinkSingleValue { [weak self] in
                switch $0 {
                case .success(let (user, token)):
                    Log.info("connectUser user:\(user) token:\(token)")
                    self?.connectUserImpl(user, token)
                    self?.setupChannelListController(withUserId: user.id)
                case let .failure(error):
                    // TODO: pop up an alert that lets the user retry fetching their chat token from our backend
                    Log.error("Couldn't show chat. either user or reclip chat token weren't available: \(error)")
                }
            }
    }
```

**Comment by AndrewSB** [comment]
appreciate it @polqf.

**Comment by AndrewSB** [comment]
made the change, but i'm still seeing the error. less often maybe? but still happening

```
2023-02-24 11:02:49.732 [ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:67] [decodeRequestResponse(data:response:error:)] > API request failed with status code: 401, code: 5 response:
{
  "code" : 5,
  "message" : "QueryChannels failed with error: \"stream-auth-type missing or invalid\"",
  "details" : [

  ],
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "StatusCode" : 401,
  "duration" : "0"
})
```

i updated that issue you found to work like this instead

<img width="839" alt="Screenshot 2023-02-24 at 11 03 13 AM" src="https://user-images.githubusercontent.com/3814772/221269038-cb3d8c58-9456-41b2-8d84-72e0b73702c3.png">

**Comment by AndrewSB** [comment]
maybe it could be useful for your framework to internally log an error & allow a breakpoint to be sent whenever a request without an auth header is set? that way it'll be easier to find these issues.

or even just fail faster, and not even send the request if all requests without authentication will fail?

**Comment by figelwump** [comment]
We are seeing this issue as well, in the latest `4.28.0` release. Note that we did not have this in the `4.21.1` release, with the same codebase. So it seems to have been introduced in the SDK sometime in the interim. 

Code snippet:
```
    guard let chatClient = self.chatClient else {
      assertionFailure("Must call initClient() before creating channelController")
      throw MessagesManagerErrors.invalidClient
    }

    let channelController = chatClient.channelController(
      for: try ChannelId(cid: channelId)
    )

    return try await withCheckedThrowingContinuation { continuation in
      channelController.synchronize { [weak self] error in
        guard let self = self else { return }

        if let error = error {
          self.logger.warning("Error when syncing the Stream channel: \(error)")
          continuation.resume(throwing: MessagesManagerErrors.connectFailed)
        } else {
          continuation.resume(returning: channelController)
        }
      }
    }
```

`channelController.synchronize` is returning an error sporadically:
```
Error when syncing the Stream channel: Error ClientError in .../stream-chat-swift/Sources/StreamChat/APIClient/RequestDecoder.swift:71 -> ServerErrorPayload(code: 5, message: "GetOrCreateChannel failed with error: "stream-auth-type missing or invalid"", statusCode: 401)).
```

This is sporadic, maybe 1 out of 10 times, not clear what triggers it, but when it happens it significantly breaks the functionality. Sounds like sometimes `stream-auth-type` header is not being set (or set incorrectly) by the SDK. For now we have reverted back to 4.21.1 and seems fine.

**Comment by ferhatabd** [comment]
Hey @polqf! 
We've been seeing this issue I think since 4.24 - back then we went back to 4.21 and continued working that way. 
But now that we have to use some changes in the main branch, we are again seeing the same issue. 
Did some debugging and I think the issue is that the `connectUser` callback is never called in some cases, what seems to be in a random fashion. 
I can see that whenever [this scheduler](https://github.com/GetStream/stream-chat-swift/blob/999b5aabfe4af6b1d960d8222ae200e2b2bfaa29/Sources/StreamChat/Repositories/AuthenticationRepository.swift#L259) fires, it works normally. But in some cases it just doesn't and the session is never instantiated correctly. Which is why the subsequent calls to the SDK (like channel queries etc) fails with 401s. 
Since we don't have much control over this, first thing I did was to make sure that the calls to the `connectUser` are done on the main thread. And if we don't get a callback in 5s, I call `connectUser` again. This seems to be working so far but it's just a workaround and would be really great if we can get to the bottom of this. 
PS: When we do retry and it works, we still get back only one callback. I think there is a buffer implemented in the `AuthenticationRepository` but this first callback never comes back.

**Comment by polqf** [comment]
We seem to have identified the issue. It relies with the fact that while you are connecting to the chat, you might be starting requests to load resources. When that happens, and if the internet connection is not ideal, it might happen that while waiting for the token to be retrieved, we end up timeout'ing. In that case, we are mistakenly sending the request without authentication headers and that's returning an expected 401. We are working on the fix for it and will keep you posted.

One thing that you might want to look at is whether you are waiting for the chat to be fully connected before performing any requests to load resources or not, this would validate this theory.

**Comment by ferhatabd** [comment]
het @polqf thank you for the update! while I can confirm the `401`s seem to have disappeared, we are still seeing the issue related to the callback I described [here](https://github.com/GetStream/stream-chat-swift/issues/2431#issuecomment-1463733163). 
I'll check this a bit more and maybe create a new issue if I still don't / can't see something we are doing wrong.

**Comment by polqf** [comment]
Hi @ferhatabd , please do open another issue so we can focus on it. 
Would be nice to understand if you are recreating the client (or other objects) that can lead to that. We will continue investigating it from our side as well.

**Comment by martinmitrevski** [comment]
@davitykale our next release is planned for mid-end of next week, it will be available on `main` then.
