### ISSUE TITLE
Creating Channel Without Name

### ISSUE THREAD

**Issue by ashishrnf** [GetStream/stream-chat-swift#2582]
## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context
Hi, when we creating Direct Message then it is creating DM with name. See in attached screen shot and error data.
Here I am sharing information which is required for you for investigation purpose.
Stream Chat Version and Framework = 'StreamChat', '~> 4.28.0' 'StreamChatUI', '~> 4.28.0'
iOS Version = 15.2, 16.2, 16.4 etc
Swift Language Version = Swift 4
Xcode Version = 14.1
Device = iPhone 12, iPhone XR etc..
Please see this issue ASAP. 
Thanks
Ashish Tiwari

![IMG_0231](https://user-images.githubusercontent.com/119917873/234499987-5d9b7d5c-68f0-479d-a234-52e9c196037b.PNG)

https://user-images.githubusercontent.com/119917873/234500044-3f1839b2-29c1-45b9-a7a4-0ab844074659.mp4

[errorMsgOnCreatingChannel_Stream.pdf](https://github.com/GetStream/stream-chat-swift/files/11330120/errorMsgOnCreatingChannel_Stream.pdf)

**Comment by ashishrnf** [comment]
Hi poloqf,
After getting successful response from server I have integrated following code:
  DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                        let chatScreen = ChatChannelViewController()
                        chatScreen.channelController = ChatClient.shared?.channelController(for: ChannelId.init(type: .messaging, id: JSONResponse["id"].stringValue))
                        chatScreen.isFromCreate = true
                        chatScreen.eType = .messaging
                        self.navigationController?.pushViewController(chatScreen, animated: true)
                    }


Stream Chat Initialisation code:  
var config = ChatClientConfig(apiKey: .init(userInfo.stream_app_id)) 
               config.applicationGroupIdentifier = "group.com.netgym"
                let userId = HelperClass().getUserID() 
                let token = try! Token.init(rawValue: userInfo.stream_token)
                 /// Step 1: create an instance of ChatClient and share it using the singleton
                    ChatClient.shared = ChatClient(config: config)

                    /// Step 2: connect to chat
                    ChatClient.shared?.connectUser(
                        userInfo: UserInfo(
                            id: userId,
                            name: userInfo.sFullName,
                            imageURL: URL(string: userInfo.sProfileImage)
                        ),
                        token: token
                    )
                
                let sDeviceToken = UserDefaults.standard.object(forKey: "device_token_data") as? Data
                if sDeviceToken != nil {
                   // let deviceToken = Data(sDeviceToken.utf16)
                    ChatClient.shared?.currentUserController().addDevice(.apn(token: sDeviceToken!, providerName: "Netgym")) { error in
                            if let error = error {
                                log.warning("adding a device failed with an error \(error)")
                            }
                        }
                }
                Please don't ask anything I have discussed with you team to the following ticket number 2533. Please check. I had given all details.

**Comment by polqf** [comment]
Hi @ashishrnf ,

This is not enough information for us to help you.
Are you sure you are successfully creating the channel? Where are you creating it and how?

Also, seems like your connect logic is not listening to the completion block, that would be advisable.

**Comment by ashishrnf** [comment]
Hi polqf,
Channel creating with name but when we creating more than 10, 20 channel continuously then it create random one channel without name. so here my logic integration is right. otherwise  it create channel without name every time. although I am giving information below of channel creation. So please check and tell me what is missing in this logic.
first make api call and  getting response from server :
{
  "message" : "Direct message created successfully",
  "is_exist" : false,
  "status" : 200,
  "id" : "921486c0-d1f6-4fb7-abf5-4abc0ef24464"
}
Then we this id we send to Stream Chat for creating channel/DM  code is given below:
 let chatScreen = ChatChannelViewController()
                        chatScreen.channelController = ChatClient.shared?.channelController(for: ChannelId.init(type: .messaging, id: JSONResponse["id"].stringValue))
                        chatScreen.isFromCreate = true
                        chatScreen.eType = .messaging
                        self.navigationController?.pushViewController(chatScreen, animated: true)
                        
Here ChatChannelViewController extend Stream ChatChannelVC such type 
class ChatChannelViewController: ChatChannelVC {

}


Please Check Direct Message with out name occurs 5 times out of 100. actual this is core data related issue from stream side. continuous creating channel some time stream is unable to save this Direct message Data and giving nil value so it display Direct message without name. So please check it.
Thanks
Ashish Tiwari

**Comment by polqf** [comment]
Hi @ashishrnf. 
Please share the logic to create the channel, not the logic to show it.

**Comment by ashishrnf** [comment]
HI @polqf 
thank you for your response 

According to my Understanding the problem is with 

chatScreen.channelController = ChatClient.shared?.channelController(for: ChannelId.init(type: .messaging, id: JSONResponse["id"].stringValue))

 ChannelId.init is not able to load the Group data payload properly first time and when navigate back and open the same group the Group is able to load with proper name and this is the issue I have been facing. 

hope this defines the problem and if you are still not able to reproduce the issue I will be happy to share the SDK version details and more data related to the issue please confirm the same .

**Comment by ashishrnf** [comment]
Hi
Any update on this.

Thanks
Ashish Tiwari

**Comment by polqf** [comment]
Hi @ashishrnf , you are only sharing the code to create the channel controller, but not the code to create the channel itself.
Where does `JSONResponse` come from? Who is calling the Stream APIs to create the channel?

**Comment by ashishrnf** [comment]
Hi
Here is the code to create a channel 

 AFWrapper.createGroupChat(dictData: self .setJson(),docData: self.docData,imageExtenstion: self.imgExtension,success: {
                (JSONResponse) -> Void in
                print(JSONResponse)
                MBProgressHUD.hide(for: self.view, animated: true)
                let sStatus = JSONResponse["status"].stringValue
                if sStatus == "200" {

and set JSON Definition 
 func setJson() -> Dictionary <String , Any>
    {
        var dictMain = Dictionary <String , Any>()
        dictMain = ["receivers" : self.getSelectedAudienceIds(),"type" : "group_chat","message" : "", "is_private" : true]
        print(dictMain)
        return dictMain
    }
    
    Thank you, Looking forward for the response.

**Comment by ashisht85** [comment]
Hi,
Please check the attached video in this thread. all flow until get the crash after login. and what you want from me please explain clearly.

**Comment by nuno-vieira** [comment]
Hi @ashisht85,

You will need to explain clearly, what you are trying to do since, as of now, we can't understand your use case.

Either way, channels do not have a name by default. The only way they have names out of the box is if you create a channel without ID and with DM members like it explains [here](https://getstream.io/chat/docs/ios-swift/creating_channels/?language=swift#2.-creating-a-channel-for-a-list-of-members).

If you are creating a channel, it is probably better you use these functions instead:
- If you want to create a Group Channel: [`client.channelController(createChannelWithId:)`](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/Controllers/ChannelController/ChatClient%2BChannelController.swift#L129)
- If you want to create a DM Channel: [`client.channelController(createDirectMessageChannelWith:)`](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/Controllers/ChannelController/ChatClient%2BChannelController.swift#L72)

Also, it is important to understand the differences between a DM Channel and Group Channel. DM Channel can have multiple members, but you can't change the members after you create the channel (just like Slack). Group Channels, you can change the members whenever you want. 

The errors you are having are most likely because you are trying to access a channel which has not been created yet, and so CoreData says that the channel doesn't exist in the local DB. 

Best,
Nuno

**Comment by ashishrnf** [comment]
Hi,
I am creating channel DM. So after creating this channel DM member is
missing . That why I am telling you.

**Comment by nuno-vieira** [comment]
@ashishrnf

From what I can understand, the problem is that Stream API is not able to find your channel. What do you mean by the member is missing? 

You are mentioning so many issues that I don't understand what issue you are currently having. Can you please, 1st, explain what you want to do and what is your use case? And then, can you explain what is the issue you are having? I'm a bit confused now. You mention channels don't have names, then channels don't have members, and then CoreData crashes... Can we focus on one issue at a time?

Thank you,
Nuno

**Comment by ashishrnf** [comment]
Ok. Leave this for now. Focus only one.

Thanks
Ashish Tiwari

**Comment by nuno-vieira** [comment]
Hi @ashishrnf,

All these issues seem to be integration issues on your side. Please reach out to support@getstream.io, and create one ticket per issue. Our support team will try to help you with the integration as much as possible., although keep in mind we only offer integration calls to Enterprise Customers.

Best,
Nuno
