### ISSUE TITLE
Video Attachments Do Not Have Audio in iOS

### ISSUE THREAD

**Issue by sahilprocore** [GetStream/stream-chat-swift#2673]
## What did you do?
Attached a video to messages. Able to play it but no audio on iOS which calls GetStream's GalleryAttachmentViewInjector `handleTapOnAttachment`

## What did you expect to happen?
Expected audio to play on iOS

## What happened instead?
No Audio was played on iOS but audio was playing on Web

## GetStream Environment
**GetStream Chat version:** StreamChat: 4.20.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.4
**Swift version:** 5.8.1
**Xcode version:** 14.3
**Device:** Tested on iPhone 11 and iPhone 14

**Comment by sahilprocore** [comment]
Forgot to add: audio is playing on web

**Comment by sahilprocore** [comment]
Hi @polqf 

Sent it from iOS. FWIW: I've tried multiple videos and I'm attaching them via the iOS gallery (using AnyAttachmentPayload with the attachmentType .video) and not as a files attachment.

I am attaching one of the videos below.

Thank you!


https://github.com/GetStream/stream-chat-swift/assets/104792244/c7c8450e-379a-4ead-9bf0-1f929cf3b52e

**Comment by testableapple** [comment]
Hi @sahilprocore,
Thanks for reporting this.

We've never experienced such an issue before, so please let me ask you a couple of questions:

- Do you test this on iOS Simulator or an actual device? Even though everything should work smoothly on both, please ensure the problem still reproduces on an actual device with enabled sound.
- If you upload an audio attachment, does it produce sound when playing?
- Have you tried to create a new empty/simple project with StreamChat integrated and make sure you still don't have audio on video attachments?
- Have you seen [our documentation](https://getstream.io/chat/docs/sdk/ios/uikit/guides/working-with-attachments/) around working with attachments?
- Could you try to upload the same attachment in our [DemoApp](https://github.com/GetStream/stream-chat-swift/tree/develop/DemoApp)?
- If nothing helps, could you try to upgrade to the latest version (4.33.0 as of now) and confirm if the issue is still there?

Best wishes,
Alexey

**Comment by sahilprocore** [comment]
Yep sorry this was an incorrect permissions issue. Thank you for your timely response
