### ISSUE TITLE
In iOS Native How will we open thread reply screen with all thread message from push notification

### ISSUE THREAD

**Issue by ashishrnf** [GetStream/stream-chat-swift#2713]
## What did you do?
I want to open thread reply screen with all thread text msg on click on push notification.on push notification I have only channel I'd and message I'd. So please help to open thread reply screen with old thread text msg.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by ashishrnf** [comment]
Please write code to open thread reply screen with all old thread message from appdelegate on click on push notification.

**Comment by testableapple** [comment]
Hi @ashishrnf,

If you use the `ChatChannelVC` with a query of .around(messageId), this will work automatically. Read more about `ChatChannelVC` [here](https://getstream.io/chat/docs/sdk/ios/uikit/components/channel/). Hope this helps.

Best,
Alexey

**Comment by ashishrnf** [comment]
Hi, please write the dummy  code with dummy message I'd etc to open thread reply window with all old thread message.

**Comment by ashisht85** [comment]
Hi, 
I want to open direct Thread Reply screen from AppDelegate.swift with all old thread message on click on Thread reply push notification. Please tell me the code which is navigating direct Thread Reply screen with all old thread msg. From ChatChannelVC we are able to open thread reply screen. but unable to open this directly. Please write the code with dummy message and channel id so that we can integrate this and open thread reply window directly after getting reply thread push notification. Here I am using latest stream chat SDK ver 4.34.0. Please help..
