### ISSUE TITLE
.or filter in swift isn't working

### ISSUE THREAD

**Issue by arnav-webknot** [GetStream/stream-chat-swift#2755]
## What did you do?
```
let filters: [Filter<ChannelListFilterScope>] = [
    .and([
        .equal(.init(rawValue: "type"), to: "messaging"),
        .in(.init(rawValue: "members"), values: [id]),
        .equal(.init(rawValue: "programUuid"), to: programId),
        .or([
            .equal(.init(rawValue: "channel_type"), to: "program_admin_channel"),
            .equal(.init(rawValue: "channel_type"), to: "program_admin_one_to_one")
        ])
    ])
]
```
## What did you expect to happen?
Filtering should contain items with channel_type of program_admin_channel or program_admin_one_to_one

## What happened instead?
Filtering is giving empty list

## GetStream Environment
**GetStream Chat frameworks: *StreamChat, StreamChatSwiftUI*
**iOS version: *iOS 16.6*
**Swift version: *5.8*
**Xcode version: *14.3*
**Device: *All simulator and real device*

**Comment by nuno-vieira** [comment]
Hello @arnav-webknot,

Some notes on your query:
- `.equal(.init(rawValue: "type"), to: "messaging")`, should be written like so: `.equal(.type, to: "messaging")`, all properties which come by default from the SDK, should be written like that.
- `.in(.init(rawValue: "members"), values: [id])` should be written like so `.containMembers(userIds: [id])`
- `.equal(.init(rawValue: "channel_type"), to: "program_admin_one_to_one")` can be written like so: `.equal( "channel_type", to: "program_admin_one_to_one")` when using custom propertis

We recommend you read the following docs in order to understand how filtering works, here:
https://getstream.io/chat/docs/sdk/ios/client/controllers/channels/#1-create-a-query

It seems like you are using extraData properties for filtering, so in that case, you need to provide a filter block like it is described in the docs.

Another question I have is what is the difference between `channel_type` and our own `type`?  If you remove this one `.equal(.init(rawValue: "type"), to: "messaging")` does it work?

Best,
Nuno

**Comment by arnav-webknot** [comment]
I tried all the recommended fixes yet it is still not working as intended. Channel_type is a custom field we have created.

**Comment by nuno-vieira** [comment]
@arnav-webknot can you try using a different key? `channel_type` could be clashing with an internal key of our own. 

Either way, can you share the actually HTTP request that it is performing? You can share it by using a Proxy like https://proxyman.io/ or by using our logger like so:
```swift
LogConfig.level = .debug
LogConfig.subsystems = .httpRequests
```

**Comment by nuno-vieira** [comment]
Hello,

We are closing this one for inactivity. 

Best,
Nuno
