### ISSUE TITLE
Compilation of StreamChatTestMockServer and StreamChatTestTools targets

### ISSUE THREAD

**Issue by mschuetz-viz** [GetStream/stream-chat-swift#2850]
## What did you do?
We're trying to use Stream's mock server to implement some UI tests for our chat solution. I was investigating another issue when I noticed that on a clean fork of the`stream-chat-swift` repo I'm not able to compile the `StreamChatTestMockServer` and `StreamChatTestTools` targets, because of missing dependencies to `StreamChatTestHelpers` and `Swifter`

## What did you expect to happen?
Should compile without any issue

## What happened instead?
targets `StreamChatTestMockServer` and `StreamChatTestTools` do not compile, because of missing dependencies to `StreamChatTestHelpers` and `Swifter`

## GetStream Environment
**GetStream Chat version:** 4.39.0
**GetStream Chat frameworks:** StreamChat
**iOS version:** 16.4
**Swift version:** Swift 5.8.1
**Xcode version:** 14.3.1
**Device:** iPhone 13 Simulator

**Comment by mschuetz-viz** [comment]
I was able to overcome the compile errors with the changes made in the attached patch [stream-chat-swift.diff.zip](https://github.com/GetStream/stream-chat-swift/files/13167861/stream-chat-swift.diff.zip)

**Comment by testableapple** [comment]
Hi @mschuetz-viz,
Thanks for opening the issue.

At the moment, SwiftPM has an issue, it pulls all dependencies that are listed in `Package.swift` even if the SDK does not depend on them. It led to our customers pulling our test dependencies (e.g.: Swift, Difference, etc) when they did not require them. Because of that, we decided to remove the `StreamChatTestHelpers` dependency from `Package.swift`.

In order to use `StreamChatTestMockServer` and `StreamChatTestTools`, starting from `v4.40.0`, you need to add both `https://github.com/GetStream/stream-chat-swift` and `https://github.com/GetStream/stream-chat-swift-test-helpers` as your project dependencies.

Make sure to set an exact version of the `https://github.com/GetStream/stream-chat-swift-test-helpers` dependency, as it can be updated frequently.

Hope this helps.

Best wishes,
Alexey

**Comment by mschuetz-viz** [comment]
Thanks for your help, finally got the time to follow your hint and make it work 👌
