### ISSUE TITLE
How to create custom component for `ChatMessageDecorationView`

### ISSUE THREAD

**Issue by brianmwadime** [GetStream/stream-chat-swift#2875]
## What did you do?
We wanted to modify how the message header decorator view displays info based on state/scenarios.

## What did you expect to happen?
Expected to be able to extend `ChatMessageDecorationView`

## What happened instead?
We found that `ChatMessageDecorationView` is marked as a final class and not extendable.

Is there a way to modify the display of the Message header decorator view for system messages?

## GetStream Environment
**GetStream Chat version:** 4.40.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.7.2
**Swift version:** 5
**Xcode version:** 15
**Device:** iPhone 11 pro

**Comment by ipavlidakis** [comment]
Hey Brian,

Thanks for reaching out. `ChatMessageDecorationView` is `open` for subclass, however `ChatChannelMessageHeaderDecoratorView` is `final`. 

In order to customize the header of a message you can either start by creating a view subclassing `ChatMessageDecorationView` and inside it you can compose the view and layout you need either by using the UI components (e.g. ChatChannelMessageHeaderDecoratorView) provided by the SDK or by creating your own. 

You can find more docs around Decoration Views [here](https://getstream.io/chat/docs/sdk/ios/uikit/components/message/#decoration-views)

Kind regards,
Ilias
