### ISSUE TITLE
Unable to receive push Notifications: error "DeviceTokenNotForTopic"

### ISSUE THREAD

**Issue by kirsanov-dev** [GetStream/stream-chat-swift#3036]
I have added all the necessary code from the documentation to set up ф device and register for remote push notifications, but I don't receive a push notification every time another user sends me a message in the chat.

In the Push logs, I found the following message:
"publishing the message failed. code = "400"; error = "DeviceTokenNotForTopic"; device is disabled"

What could be the cause of this error? I suspect the issue lies somewhere in our settings. I would appreciate your help in identifying the cause if you have encountered such an issue before.

**Comment by nuno-vieira** [comment]
Hi @kirsanov-dev,

For Push Notifications related questions, since it involves the backend as well, we recommend opening a ticket on support here: https://getstream.io/contact/support/

Meanwhile, you can also share the snippet of your code when do you add the device and remove the device to see if we can see something wrong.

Best,
Nuno

**Comment by nuno-vieira** [comment]
I'm closing this one for now. Let me know if Support was able to address your issues.

Best,
Nuno
