### ISSUE TITLE
Custom subview of ChatMessageContentView is not sized correctly

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#3118]
## What did you do?
I added a custom subview of ChatMessageContentView according to docs at: https://getstream.io/chat/docs/sdk/ios/uikit/components/message/

## What did you expect to happen?
I expect that subview to display consistently for each message in the chat channel

## What happened instead?
Some of the chat message views are not sized correctly

## GetStream Environment
**GetStream Chat version:** 4.49.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17.2
**Swift version:** 5
**Xcode version:** 15.2
**Device:** iPhone 15 Pro simulator

## Additional context
I've attached a sample project. I tried to add a custom subview of ChatMessageContentView. That subview has dynamic size (based on contents of a UICollectionView). It does not always display at the correct size in the chat channel.
Steps to reproduce:
- Run attached project
- Tap Login to connect to Stream
- Tap Chat Channel
- Notice that not all of the chat messages display the custom subview at the correct size (see attached screenshot)
- Note: if you scroll the message cells offscreen and then back onscreen, they seem to resize to the correct size

[StreamDonationMessage.zip](https://github.com/GetStream/stream-chat-swift/files/14813262/StreamDonationMessage.zip)
![Simulator Screenshot - iPhone 15 Pro - 2024-03-30 at 15 16 37](https://github.com/GetStream/stream-chat-swift/assets/4721220/bb04fb4f-7c04-457b-b028-8eb0943b5c70)

**Comment by nuno-vieira** [comment]
Hi @srgray,

Yes, that is normal, unfortunately. Since our Message List is an inverted UITableView and not a UICollectionView, embedding self-resizing collection views won't work very well. Although it might be possible to build that UI with some workarounds. You can try the following:
1. If possible, use a UIStackView. If you are not expecting many tags per message, this could be enough, and the performance penalty of using a stack view won't be noticeable. 
2. The other option is to find a way to explicitly reload the cell whenever the tags grow to a specific size. One idea is to override the `ChatMessageListView.reuseIdentifier()` function which is the one responsible for calculating the cell identifier based on the `ChatMessageLayoutOption` and the message content. You could use the `tags.count`and post-fix the cell identifier to make sure that whenever the tags change, it reloads the cell 🤔 


The pseudo code for 2:
```swift
class CustomMessageListView: ChatMessageListView {
    override func reuseIdentifier(
        contentViewClass: ChatMessageContentView.Type,
        attachmentViewInjectorType: AttachmentViewInjector.Type?,
        layoutOptions: ChatMessageLayoutOptions,
        message: ChatMessage?
    ) -> String {
        var identifier = super.reuseIdentifier(
            contentViewClass: contentViewClass,
            attachmentViewInjectorType: attachmentViewInjectorType,
            layoutOptions: layoutOptions,
            message: message
        )
        if message.tags.count > 0 {
            identifier += "_\(message.tags.count)"
        }
        return identifier
    }
}
```

Let us know if you were able to find a workaround for this. 

Best,
Nuno

**Comment by nuno-vieira** [comment]
@srgray We have a similar UI in our Slack Example App. We use a collection view there, but we have a height constraint that we change depending on the number of reactions.

The code:
- https://github.com/GetStream/stream-chat-swift/blob/develop/Examples/SlackClone/SlackChatMessageContentView.swift
- https://github.com/GetStream/stream-chat-swift/blob/develop/Examples/SlackClone/SlackReactionsView.swift

This works best whenever the collection view has a predictable number of items per row since we can do this to calculate the height constraint:
```swift
let numberOfItemsPerRow = 3
let numberOfRows = Double(reactions.count).truncatingRemainder(dividingBy: numberOfRows)
heightConstraint?.constant = ceil(numberOfRows) * reactionRowHeight
```

But yeah, these use cases are a bit tricky when working with a UITableView, unfortunatly it is a short-coming of our Message List at the moment, and solving it completely would require refactoring it to a UICollectionView, which we are not planning to do at the moment. 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @srgray,

Did one of the solutions provided work for you? If yes, which option did you choose?

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hey @srgray,

I'm closing this for now. Feel free to reply and re open it in case you are still having problems or want to share your solution.

Best,
Nuno

**Comment by srgray** [comment]
@nuno-vieira Hi Nuno, sorry for late response. I decided to go with the UIStackView recommendation, since we don't have a fixed number of items per row (variable width). It seems to be sized correctly to fit all of the items. Thanks for the recommendation.
