### ISSUE TITLE
Duplicate Issue

### ISSUE THREAD

**Issue by iosiappmemes** [GetStream/stream-chat-swift#844]
Demo app showing duplicate DM in conversation list .

![image](https://user-images.githubusercontent.com/54673061/109005199-b1e7d300-76cf-11eb-94ca-a28634b6b90b.png)

**Comment by VojtaStavik** [comment]
Hi @iosiappmemes , are you referring to the "MemesOfficials" channels? Are you sure these are not 2 different channels just with a same name and avatar? I'm asking because based on the screenshot, the last received message for both of them is different. This is not just a visual glitch.

If you're sure those are the same channel, please share with me more information about your StreamChat App ID + what is the `cid` of the channel.

**Comment by iosiappmemes** [comment]
Hi @VojtaStavik 
Thank you for response, i already resolved this issue at my end , after waiting long time form your End. Yes you are right it was two different users.
Thank you .

**Comment by VojtaStavik** [comment]
@iosiappmemes, when you open a new issue, you're offered a template with specific questions regarding your iOS version and the version of the SDK you use. These things help us to solve problems more quickly. In case you have an urgent request, it's usually better to use the official support e-mail you can find in your Chat App dashboard.
